development:
    adapter: mysql2
    database: rails4_start_development
    username: root
    password: vagrant
    #socket: /private/tmp/mysql.sock
    socket: /var/run/mysqld/mysqld.sock

test:
    adapter: mysql2
    database: rails4_start_test
    username: root
    password: vagrant
    #socket: /private/tmp/mysql.sock
    socket: /var/run/mysqld/mysqld.sock
